language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $TRAVISTOKEN
 local_dir: dist
 verbose: true
 on:
   branch: develop